[package]
name = "cryoglyph"
description = "Fast, simple 2D text rendering for wgpu. A fork of glyphon for iced."
version = "0.1.0"
edition = "2024"
authors = ["Héctor Ramón Jiménez <hector@hecrj.dev>"]
repository = "https://github.com/iced-rs/cryoglyph"
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
wgpu = { version = "27", default-features = false, features = ["wgsl"] }
etagere = "0.2"
cosmic-text = { git = "https://github.com/playtron-os/cosmic-text.git", rev = "e07f8b6" }
lru = { version = "0.16", default-features = false }
rustc-hash = "2"

[dev-dependencies]
winit = "0.30"
pollster = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "prepare"
harness = false
